% go-sgb: Knuth의 Stanford GraphBase를 한글 GWEB로 옮긴 것.
% 이 파일은 test_sample.w를 Go로 이식한다.
@i types.w

\input kotexgweb
\def\title{TEST\_\,SAMPLE}

@* 들어가며. 이 프로그램은 Stanford GraphBase를 설치할 때만 쓴다. 가장 중요한
서브루틴들을 불러, 올바른 출력과 대조할 수 있는 파일을 만든다. 시험이 빈틈없지는
않지만, 이식성 오류---시스템마다 결과가 달라질 수 있는 경우---를 잡아내도록
짜였다. 그래서 아무 탈이 없으면 GraphBase 루틴들이 제대로 설치됐다고 볼 수 있다.

기본 발상은 간단하다: 그래프를 하나 만들어 그 두드러진 특징 몇 가지를 찍고,
다음 그래프로 넘어간다. 출력이 저자가 Stanford에서 만든 ``올바른'' 출력 파일과
맞으면 시험을 통과한 것이다. 출력은 둘이다. 그래프 특징을 담은 주 출력은 표준
출력이고, 다른 하나인 \.{test.gb}는 |SaveGraph|로 아스키 형식으로 저장한
그래프다.

@ 프로그램의 뼈대다. 자료 파일은 생성기 기본값(\.{/usr/local/sgb/data})에서
읽으므로 |dir|에 빈 문자열을 넘긴다.

@c
package main

import (
	"errors"
	"fmt"
	"strings"
	@#
	"github.com/sjnam/go-sgb/gbbasic"
	"github.com/sjnam/go-sgb/gbbooks"
	"github.com/sjnam/go-sgb/gbecon"
	"github.com/sjnam/go-sgb/gbgames"
	"github.com/sjnam/go-sgb/gbgates"
	"github.com/sjnam/go-sgb/gbgraph"
	"github.com/sjnam/go-sgb/gblisa"
	"github.com/sjnam/go-sgb/gbmiles"
	"github.com/sjnam/go-sgb/gbplane"
	"github.com/sjnam/go-sgb/gbraman"
	"github.com/sjnam/go-sgb/gbrand"
	"github.com/sjnam/go-sgb/gbroget"
	"github.com/sjnam/go-sgb/gbsave"
	"github.com/sjnam/go-sgb/gbwords"
)

// |dst|는 빈도 50\%, 25\%, 25\%인 확률 분포다.
var dst = []int64{0x20000000, 0x10000000, 0x10000000}

@<표본 찍기 서브루틴@>

func main() {
	fmt.Println("GraphBase samples generated by test_sample:")
	@<나중에 되살릴 그래프를 저장한다@>
	@<만든 그래프들의 표본을 찍는다@>
}

@ 먼저 입력 자료도 난수도 필요 없는 그래프로 조심스레 시작한다. 이 시험이
실패하면 잘못은 {\sc GB\_\,GRAPH}나 {\sc GB\_\,RAMAN}에 있다. |reduce|에 4를
넘기는데, 0이 아니면 어느 값이든 자기 고리·중복 간선을 없애며 표식에는 그 값이
그대로 찍힌다.

@<만든 그래프들의 표본을 찍는다@>=
g, err := gbraman.Raman(31, 3, 0, 4)
printSample(g, err, 4)

@ 다음은 |w>>=1| 연산의 해석에 기대는 {\sc GB\_\,BASIC}의 일부를 시험한다.
좌표 32와 33만 감싸져야 한다.

@<만든 그래프들의 표본을 찍는다@>=
g, err = gbbasic.Board(1, 1, 2, -33, 1, -0x40000000-0x40000000, true)
printSample(g, err, 2000)

@ {\sc GB\_\,BASIC}의 또 다른 시스템 의존 부분을 문자 코드로 시험한다.

@<만든 그래프들의 표본을 찍는다@>=
g, err = gbbasic.Subsets(32, 18, 16, 0, 999, -999, 0x80000000, true)
printSample(g, err, 1)

@ 저장했던 그래프를 되살리고 길이를 무작위로 매긴 뒤 |Gunion|으로 합친다.

@<만든 그래프들의 표본을 찍는다@>=
g, err = gbsave.RestoreGraph("test.gb")
if err != nil {
	printSample(g, err, 2)
} else if lerr := gbrand.RandomLengths(g, false, 10, 12, dst, 2); lerr != nil {
	fmt.Printf("\nFailure code %v returned by random_lengths!\n", lerr)
} else {
	gg, _ := gbrand.RandomGraph(3, 10, 1, true, false, nil, dst, 1, 2, 1)
	u, uerr := gbbasic.Gunion(g, gg, true, false)
	printSample(u, uerr, 2)
}

@ RISC 회로의 부분 평가는 포인터 재주를 꽤 쓰므로 이식성을 잘 시험한다.
|Risc(0)|은 레지스터 수가 범위 밖이라 16으로 맞춰져 표식이 |risc(16)|이 된다.

@<만든 그래프들의 표본을 찍는다@>=
rg, rerr := gbgates.Risc(0)
if rerr != nil {
	printSample(rg, rerr, 79)
} else {
	var buf strings.Builder
	g, err = gbgates.PartialGates(rg, 1, 43210, 98765, &buf)
	printSample(g, err, 79)
}

@ 이제 자료 파일 읽기, {\sc GB\_\,SORT} 정렬, 무거운 무작위화를 시험한다. 이
절에서 많은 계산이 일어난다.

@<만든 그래프들의 표본을 찍는다@>=
g, err = gbbooks.Book("homer", 500, 400, 2, 12, 10000, -123456, 789, "")
printSample(g, err, 81)
g, err = gbecon.Econ(40, 0, 400, -111, "")
printSample(g, err, 11)
g, err = gbgames.Games(60, 70, 80, -90, -101, 60, 0, 999999999, "")
printSample(g, err, 14)
g, err = gbmiles.Miles(50, -500, 100, 1, 500, 5, 314159, "")
printSample(g, err, 20)
g, err = gblisa.PlaneLisa(100, 100, 50, 1, 300, 1, 200, 2975050, 11900200, "")
printSample(g, err, 1294)
g, err = gbplane.PlaneMiles(50, 500, -100, 1, true, 40000, 271818, "")
printSample(g, err, 14)
g, err = gbrand.RandomBigraph(300, 3, 1000, -1, nil, dst, -500, 500, 666)
printSample(g, err, 3)
g, err = gbroget.Roget(1000, 3, 1009, 1009, "")
printSample(g, err, 40)

@ 마지막으로 첫 번째는 실패하고 두 번째는 성공해야 하는 까다로운 시험이다. 무게
벡터가 {\sc GB\_\,WORDS}가 허용하는 최대 무게 문턱을 아슬아슬하게 넘는다.

@<만든 그래프들의 표본을 찍는다@>=
wtVector := []int64{100, -80589, 50000, 18935, -18935, 18935, 18935, 18935, 18935}
g, err = gbwords.Words(100, wtVector, 70000000, 69, "")
printSample(g, err, 5)
wtVector[1]++
g, err = gbwords.Words(100, wtVector, 70000000, 69, "")
printSample(g, err, 5)
g, err = gbwords.Words(0, nil, 0, 69, "")
printSample(g, err, 5555)

@ {\sc GB\_\,BASIC}의 |vertOffset| 포인터 재주가 |Complement|와 |Gunion|에 두루
쓰이므로, 무작위 멀티그래프와 그 여그래프를 저장해 나중에 되살린다. 딸린 정점
하나("Testing")도 |AllocVertex|로 만들어 |gg|의 그래프 유틸리티 |WW.V|에 매달아,
{\sc GB\_\,SAVE}가 배열 밖 정점 포인터도 제대로 저장하는지 함께 시험한다.

@<나중에 되살릴 그래프를 저장한다@>=
sg, serr := gbrand.RandomGraph(3, 10, 1, true, false, nil, dst, 1, 2, 1)
if serr == nil {
	gg, cerr := gbbasic.Complement(sg, true, true, false)
	if cerr == nil {
		gg.WW.V = gg.AllocVertex("Testing")
		gg.SetUtilType(10, 'V')
		gbsave.SaveGraph(gg, "test.gb")
	}
}

@* 표본 자료 찍기. GraphBase 형식의 그래프 |g|와 정수 |n|이 주면,
|printSample(g,err,n)|은 |g|의 이름·크기 같은 전역 특징과 |n|번째 정점의 자세한
정보를 찍는다. 생성기가 오류를 냈으면 그 panic 코드를 찍는다.

@<표본 찍기 서브루틴@>=
func printSample(g *gbgraph.Graph, err error, n int64) {
	fmt.Println()
	if g == nil {
		@<panic 코드를 찍는다@>
		return
	}
	@<|g|의 전역 특징을 찍는다@>
	@<|n|번째 정점의 정보를 찍는다@>
}

@ \CEE/의 전역 |panic_code|는 이 포팅에서 |gbgraph.PanicCode| 오류 값이다.

@<panic 코드를 찍는다@>=
var pc gbgraph.PanicCode
if errors.As(err, &pc) {
	fmt.Printf("Ooops, we just ran into panic code %d!\n", int64(pc))
} else {
	fmt.Printf("Ooops, we just ran into panic code %v!\n", err)
}

@ @<|g|의 전역 특징을 찍는다@>=
fmt.Printf("\"%s\"\n%d vertices, %d arcs, util_types %s",
	g.ID, g.N, g.M, g.UtilTypes)
s := g.UtilTypes
prUtil(&g.UU, s[8], 0, s)
prUtil(&g.VV, s[9], 0, s)
prUtil(&g.WW, s[10], 0, s)
prUtil(&g.XX, s[11], 0, s)
prUtil(&g.YY, s[12], 0, s)
prUtil(&g.ZZ, s[13], 0, s)
fmt.Println()

@ @<|n|번째 정점의 정보를 찍는다@>=
fmt.Printf("V%d: ", n)
if n >= g.N || n < 0 {
	fmt.Println("index is out of range!")
} else {
	prVert(&g.Vertices[n], 1, g.UtilTypes)
	fmt.Println()
}

@ |g.UtilTypes|가 얼마나 많은 정보를 찍을지 정한다. 자세한 방식에서는 정점이나
호를 가리키거나 정수·문자열을 담은 유틸리티 필드를 모두 찍는다. |l|이 0 이하면
간결하게 찍는다.

@<표본 찍기 서브루틴@>=
func prVert(v *gbgraph.Vertex, l int64, s string) {
	if v == nil {
		fmt.Print("NULL")
		return
	}
	if gbgates.IsBoolean(v) {
		fmt.Print("ONE") // {\sc GB\_\,GATES} 참고
		return
	}
	fmt.Printf("\"%s\"", v.Name)
	prUtil(&v.U, s[0], l-1, s)
	prUtil(&v.V, s[1], l-1, s)
	prUtil(&v.W, s[2], l-1, s)
	prUtil(&v.X, s[3], l-1, s)
	prUtil(&v.Y, s[4], l-1, s)
	prUtil(&v.Z, s[5], l-1, s)
	if l > 0 {
		for a := v.Arcs; a != nil; a = a.Next {
			fmt.Print("\n   ")
			prArc(a, 1, s)
		}
	}
}

@ @<표본 찍기 서브루틴@>=
func prArc(a *gbgraph.Arc, l int64, s string) {
	fmt.Print("->")
	prVert(a.Tip, 0, s)
	if l > 0 {
		fmt.Printf(", %d", a.Len)
		prUtil(&a.A, s[6], l-1, s)
		prUtil(&a.B, s[7], l-1, s)
	}
}

@ 유틸리티 필드 하나를 그 타입 부호에 따라 찍는다. |l|이 음수면 포인터는
건너뛰어 무한 재귀를 막는다.

@<표본 찍기 서브루틴@>=
func prUtil(u *gbgraph.Util, c byte, l int64, s string) {
	switch c {
	case 'I':
		fmt.Printf("[%d]", u.I)
	case 'S':
		if u.S != "" {
			fmt.Printf("[\"%s\"]", u.S)
		} else {
			fmt.Print("[\"(null)\"]")
		}
	case 'A':
		if l < 0 {
			return
		}
		fmt.Print("[")
		if u.A == nil {
			fmt.Print("NULL")
		} else {
			prArc(u.A, l, s)
		}
		fmt.Print("]")
	case 'V':
		if l < 0 {
			return
		}
		fmt.Print("[")
		prVert(u.V, l, s)
		fmt.Print("]")
	}
}

@* 색인.
