% go-sgb: Knuth의 Stanford GraphBase를 한글 GWEB로 옮긴 것.
% 이 파일은 test_sample.w를 Go로 이식한다.
@i gbtypes.w

\input kotexgweb
\def\title{TEST\_\,SAMPLE}

@* 들어가며. 이 프로그램은 Stanford GraphBase를 설치할 때만 쓴다. 가장 중요한
서브루틴들을 불러, 올바른 출력과 대조할 수 있는 파일을 만든다. 시험이 빈틈없지는
않지만, 이식성 오류---시스템마다 결과가 달라질 수 있는 경우---를 잡아내도록
짜였다. 그래서 아무 탈이 없으면 GraphBase 루틴들이 제대로 설치됐다고 볼 수 있다.

{\sc TEST\_\,SAMPLE}의 기본 발상은 아주 간단하다. 그래프를 하나 만들어 그
두드러진 특징 몇 가지를 찍고, 그래프를 되돌린 뒤 또 하나를 만들고, 이렇게
되풀이한다. 출력 파일이 저자가 Stanford에서 만든 ``올바른'' 출력 파일과 맞으면
시험을 통과한 것이다.

출력 파일은 사실 둘이다. 그래프의 특징을 담은 주 출력은 표준 출력이고, 다른
하나인 \.{test.gb}는 |SaveGraph|로 아스키 형식으로 저장한 그래프다.

@ 프로그램의 뼈대다. 시험 대상은 GraphBase의 생성기 모듈 거의 전부다.
|gbbasic|은 기본 그래프 연산, |gbbooks|는 문학 작품에서 얻은 그래프, |gbecon|은
경제 자료, |gbgames|는 미식축구 점수, |gbgates|는 논리 회로, |gblisa|는 모나
리자, |gbmiles|는 도시 간 거리, |gbplane|은 평면 그래프, |gbraman|은 라마누잔
그래프, |gbrand|는 무작위 그래프, |gbroget|은 로제 유의어 사전, |gbwords|는 다섯
글자 낱말 그래프에서 그래프를 만들고, |gbsave|는 그 결과를 아스키로 저장한다.
이들이 딛고 선 |gbgraph|와 |gbio|는 따로 부르지 않아도 함께 시험된다.

자료 파일은 생성기 기본값(\.{/usr/local/sgb/data})에서 읽으므로 |dir|에 빈
문자열을 넘긴다.

@c
package main

import (
	"errors"
	"fmt"
	"strings"
	@#
	"github.com/sjnam/go-sgb/gbbasic"
	"github.com/sjnam/go-sgb/gbbooks"
	"github.com/sjnam/go-sgb/gbecon"
	"github.com/sjnam/go-sgb/gbgames"
	"github.com/sjnam/go-sgb/gbgates"
	"github.com/sjnam/go-sgb/gbgraph"
	"github.com/sjnam/go-sgb/gblisa"
	"github.com/sjnam/go-sgb/gbmiles"
	"github.com/sjnam/go-sgb/gbplane"
	"github.com/sjnam/go-sgb/gbraman"
	"github.com/sjnam/go-sgb/gbrand"
	"github.com/sjnam/go-sgb/gbroget"
	"github.com/sjnam/go-sgb/gbsave"
	"github.com/sjnam/go-sgb/gbwords"
)

// |dst|는 빈도 50\%, 25\%, 25\%인 확률 분포다.
var dst = []int64{0x20000000, 0x10000000, 0x10000000}

@<표본 찍기 서브루틴@>

func main() {
	fmt.Println("GraphBase samples generated by test_sample:")
	@<나중에 되살릴 그래프를 저장한다@>
	@<만든 그래프들의 표본을 찍는다@>
}

@ 서브루틴 |printSample(g,err,n)|은 뒤에서 규정한다. |g|의 전역 특징과 |n|번째
정점의 국소 특징을 찍는 일을 한다.

시험은 조심스럽게 시작한다. 첫 그래프는 입력 자료도 유사난수도 필요 없는
것이라, 여기서 어긋나면 잘못은 {\sc GB\_\,GRAPH}나 {\sc GB\_\,RAMAN} 둘 중
하나에 있을 수밖에 없다. |reduce|에 4를 넘기는데, 0이 아니면 어느 값이든 자기
고리와 중복 간선을 없애며 표식에는 그 값이 그대로 찍힌다.

@<만든 그래프들의 표본을 찍는다@>=
g, err := gbraman.Raman(31, 3, 0, 4)
printSample(g, err, 4)

@ 다음은 {\sc GB\_\,BASIC}에서 `|w>>=1|' 연산의 해석에 기대는 대목을 시험한다.
좌표 32와 33만 감싸져야 한다.

\CEE/에서 이 자리는 진짜로 위태로웠다. 부호 있는 정수의 오른쪽 자리 옮김이
표준에 매이지 않아 구현마다 다를 수 있었기 때문이다. 그래서 Knuth는 이 시험이
실패하면 {\sc GB\_\,BASIC}의 색인에서 `system dependencies'를 찾아보고 변경
파일 \.{gb\_basic.ch}를 만들어 그 시스템에 맞게 고치라고 일러 두었다(변경 파일의
본보기로는 \.{queen\_wrap.ch}가 있다). \GO/에서는 그 걱정이 사라진다. 명세가
부호 있는 정수의 오른쪽 자리 옮김을 산술 자리 옮김으로 못 박아 두었기 때문이다.
그러니 이 시험은 이제 이식성 함정을 지키는 것이라기보다, |Board|의 감싸기 셈이
원본과 한 치도 다르지 않음을 확인하는 구실을 한다.

Knuth가 이 절에 붙인 위로도 함께 옮겨 둘 만하다. 이 시험 하나만 실패하고 뒤의
것들이 모두 통과한다면 GraphBase 구현은 그런대로 훌륭한 것이다. 여기서 잡히는
버그는 실제로는 좀처럼 드러나지 않기 때문이다. 스스로에게 물어보라. 나는 그런
버그와 편안히 살 수 있는가?

@<만든 그래프들의 표본을 찍는다@>=
g, err = gbbasic.Board(1, 1, 2, -33, 1, -0x40000000-0x40000000, true)
printSample(g, err, 2000)

@ {\sc GB\_\,BASIC}의 또 다른 시스템 의존 부분을 여기서 시험하는데, 이번에는
문자 코드가 걸린 자리다. \CEE/에서는 |char|의 부호 유무가 구현에 맡겨져 있어
정점 이름을 짓는 셈이 시스템마다 갈릴 수 있었다. \GO/의 |byte|는 언제나 부호가
없으니 이 역시 판가름이 나 있다.

@<만든 그래프들의 표본을 찍는다@>=
g, err = gbbasic.Subsets(32, 18, 16, 0, 999, -999, 0x80000000, true)
printSample(g, err, 1)

@ 이제 나중에 되살릴 그래프를 저장한다. \.{test.gb}가 \.{test.correct}와 맞지
않으면 가장 의심스러운 것은 {\sc GB\_\,BASIC}의 |vert_offset|이라고 Knuth는
적었다. 정점 배열 안에서 포인터를 옮겨 다니는 ``포인터 재주''인데, 워낙 여기저기
쓰이므로 반드시 제대로 돌아야 한다는 것이다. 여기서 시험하는 |Complement|와
아래에서 시험하는 |Gunion|이 바로 그것을 쓴다.

\GO/ 이식에는 포인터 산술이 없다---|gbgraph|가 정점을 조각(slice)과 색인으로
다루므로 그 함정 자체가 없다. 그래도 이 시험은 값어치를 잃지 않는다.
|Complement|와 |Gunion|이 정점을 옳게 짝지어 옮기는지, 그리고 {\sc GB\_\,SAVE}가
그 결과를 한 글자도 틀리지 않게 적어 내는지를 여전히 확인해 주기 때문이다.

@ 무작위 멀티그래프---정점 3개, 간선 10개---를 짓고 그 여그래프를 뜬다. 여그래프
|gg|는 |sg|의 사본이되 중복 간선이 없다. 여기에 딸린 정점 하나를 더 만들어
정점 배열 바깥에 두고 이름을 ``Testing''이라 붙인 뒤, 그래프 유틸리티 |WW.V|에
매달아 |gg|의 일부로 삼는다. {\sc GB\_\,SAVE}가 배열 밖 정점을 가리키는 포인터도
제대로 저장하는지 함께 보려는 것이다.

@<나중에 되살릴 그래프를 저장한다@>=
sg, serr := gbrand.RandomGraph(3, 10, 1, true, false, nil, dst, 1, 2, 1)
if serr == nil {
	gg, cerr := gbbasic.Complement(sg, true, true, false)
	if cerr == nil {
		gg.WW.V = gg.AllocVertex("Testing")
		gg.SetUtilType(10, 'V')
		gbsave.SaveGraph(gg, "test.gb")
	}
}

@ 이제 앞서 저장한 그래프를 되살리고, 그 간선 길이를 무작위로 다시 매긴다.
그런 뒤 똑같은 씨앗으로 아까와 같은 무작위 그래프를 한 번 더 지어 |Gunion|으로
합친다. 되살린 그래프와 새로 지은 그래프가 아귀가 맞아야 하므로, 저장과 복원이
한 바퀴를 온전히 돌았는지가 여기서 드러난다.

@<만든 그래프들의 표본을 찍는다@>=
g, err = gbsave.RestoreGraph("test.gb")
if err != nil {
	printSample(g, err, 2)
} else if lerr := gbrand.RandomLengths(g, false, 10, 12, dst, 2); lerr != nil {
	fmt.Printf("\nFailure code %v returned by random_lengths!\n", lerr)
} else {
	gg, _ := gbrand.RandomGraph(3, 10, 1, true, false, nil, dst, 1, 2, 1)
	u, uerr := gbbasic.Gunion(g, gg, true, false)
	printSample(u, uerr, 2)
}

@ RISC 회로의 부분 평가는 꽤 정교한 포인터 조작을 거친다. Knuth의 표현을 그대로
빌리면 ``저자가 아끼는 프로그래밍 재주''를 시험하기에 알맞은 자리다.
|Risc(0)|은 레지스터 수가 범위 밖이라 16으로 맞춰져 표식이 |risc(16)|이 된다.

@<만든 그래프들의 표본을 찍는다@>=
rg, rerr := gbgates.Risc(0)
if rerr != nil {
	printSample(rg, rerr, 79)
} else {
	var buf strings.Builder
	g, err = gbgates.PartialGates(rg, 1, 43210, 98765, &buf)
	printSample(g, err, 79)
}

@ 이제 자료 파일 읽기와 {\sc GB\_\,SORT}를 쓴 정렬, 그리고 무거운 무작위화를
시험할 차례다. 이 절에서 많은 계산이 일어난다---여덟 개의 생성기가 저마다
\.{.dat} 파일을 읽고 수만 번의 난수를 뽑는다.

@<만든 그래프들의 표본을 찍는다@>=
g, err = gbbooks.Book("homer", 500, 400, 2, 12, 10000, -123456, 789, "")
printSample(g, err, 81)
g, err = gbecon.Econ(40, 0, 400, -111, "")
printSample(g, err, 11)
g, err = gbgames.Games(60, 70, 80, -90, -101, 60, 0, 999999999, "")
printSample(g, err, 14)
g, err = gbmiles.Miles(50, -500, 100, 1, 500, 5, 314159, "")
printSample(g, err, 20)
g, err = gblisa.PlaneLisa(100, 100, 50, 1, 300, 1, 200, 2975050, 11900200, "")
printSample(g, err, 1294)
g, err = gbplane.PlaneMiles(50, 500, -100, 1, true, 40000, 271818, "")
printSample(g, err, 14)
g, err = gbrand.RandomBigraph(300, 3, 1000, -1, nil, dst, -500, 500, 666)
printSample(g, err, 3)
g, err = gbroget.Roget(1000, 3, 1009, 1009, "")
printSample(g, err, 40)

@ 마지막은 Knuth가 ``까다롭고도 까다로운'' 시험이라 부른 것으로, 첫 번째는
실패하고 두 번째는 성공해야 한다. 무게 벡터가 {\sc GB\_\,WORDS}가 허용하는 최대
무게 문턱을 아슬아슬하게 넘기 때문이다. 그 문턱 검사는 지나치게 보수적이지만,
그럼에도 지극히 온당하다고 그는 덧붙였다. 벡터의 한 성분을 1만큼 올리면 문턱
아래로 내려앉아 같은 호출이 이번에는 성공한다.

@<만든 그래프들의 표본을 찍는다@>=
wtVector := []int64{100, -80589, 50000, 18935, -18935, 18935, 18935, 18935, 18935}
g, err = gbwords.Words(100, wtVector, 70000000, 69, "")
printSample(g, err, 5)
wtVector[1]++
g, err = gbwords.Words(100, wtVector, 70000000, 69, "")
printSample(g, err, 5)
g, err = gbwords.Words(0, nil, 0, 69, "")
printSample(g, err, 5555)

@* 표본 자료 찍기. GraphBase 형식의 그래프 |g|와 정수 |n|이 주어지면,
|printSample(g,err,n)|은 |g|의 이름과 크기 같은 전역 특징을 찍고, 이어 |n|번째
정점에 대한 자세한 정보를 찍는다.

\CEE/ 원본은 여기서 |g|를 산산이 부수어 되돌리고, 부르는 쪽은 그 뒤로 |g|를
건드려서는 안 된다고 못 박는다. \GO/에는 쓰레기 수집기가 있으니 되돌릴 일이
없다---표본을 찍고 나면 |g|를 아무도 가리키지 않게 되어 저절로 사라진다. 그래서
이 이식에서는 그 금기도 함께 없어졌다.

생성기가 오류를 냈으면 그 panic 코드를 찍는다.

@<표본 찍기 서브루틴@>=
func printSample(g *gbgraph.Graph, err error, n int64) {
	fmt.Println()
	if g == nil {
		@<panic 코드를 찍는다@>
		return
	}
	@<|g|의 전역 특징을 찍는다@>
	@<|n|번째 정점의 정보를 찍는다@>
}

@ \CEE/의 전역 |panic_code|는 이 포팅에서 |gbgraph.PanicCode| 오류 값이다.
그러므로 원본과 같은 숫자를 찍으려면 오류 사슬에서 그 타입을 꺼내야 한다.

@<panic 코드를 찍는다@>=
var pc gbgraph.PanicCode
if errors.As(err, &pc) {
	fmt.Printf("Ooops, we just ran into panic code %d!\n", int64(pc))
} else {
	fmt.Printf("Ooops, we just ran into panic code %v!\n", err)
}

@ 전역 특징은 표식과 정점 수·호 수·|util_types| 문자열이고, 이어 그래프 유틸리티
여섯 개를 찍는다. |util_types| 열네 글자 가운데 뒤의 여섯이 이들의 타입이다.

@<|g|의 전역 특징을 찍는다@>=
fmt.Printf("\"%s\"\n%d vertices, %d arcs, util_types %s",
	g.ID, g.N, g.M, g.UtilTypes)
s := g.UtilTypes
prUtil(&g.UU, s[8], 0, s)
prUtil(&g.VV, s[9], 0, s)
prUtil(&g.WW, s[10], 0, s)
prUtil(&g.XX, s[11], 0, s)
prUtil(&g.YY, s[12], 0, s)
prUtil(&g.ZZ, s[13], 0, s)
fmt.Println()

@ 표본으로 고른 정점 번호가 그래프 크기를 벗어나는 일도 있다---생성기가 만든
그래프가 우리가 짐작한 것보다 작을 수 있기 때문이다. 그럴 때도 죽지 않고
그렇다고 말하고 넘어간다.

@<|n|번째 정점의 정보를 찍는다@>=
fmt.Printf("V%d: ", n)
if n >= g.N || n < 0 {
	fmt.Println("index is out of range!")
} else {
	prVert(&g.Vertices[n], 1, g.UtilTypes)
	fmt.Println()
}

@ |g.UtilTypes|가 얼마나 많은 정보를 찍을지 정한다. 여기에 자세함을 다스리는
층 매개변수 |l|이 더해진다. 가장 자세한 방식에서는 정점이나 호를 가리키거나
정수·문자열을 담은 유틸리티 필드를 모두 찍는다. |l|이 0 이하면 간결하게 찍는다.

@<표본 찍기 서브루틴@>=
func prVert(v *gbgraph.Vertex, l int64, s string) {
	if v == nil {
		fmt.Print("NULL")
		return
	}
	if gbgates.IsBoolean(v) {
		fmt.Print("ONE") // {\sc GB\_\,GATES} 참고
		return
	}
	fmt.Printf("\"%s\"", v.Name)
	prUtil(&v.U, s[0], l-1, s)
	prUtil(&v.V, s[1], l-1, s)
	prUtil(&v.W, s[2], l-1, s)
	prUtil(&v.X, s[3], l-1, s)
	prUtil(&v.Y, s[4], l-1, s)
	prUtil(&v.Z, s[5], l-1, s)
	if l > 0 {
		for a := v.Arcs; a != nil; a = a.Next {
			fmt.Print("\n   ")
			prArc(a, 1, s)
		}
	}
}

@ 호는 화살표에 이어 머리 정점을 간결하게 찍고, 자세한 방식이면 길이와 호의
유틸리티 둘을 덧붙인다.

@<표본 찍기 서브루틴@>=
func prArc(a *gbgraph.Arc, l int64, s string) {
	fmt.Print("->")
	prVert(a.Tip, 0, s)
	if l > 0 {
		fmt.Printf(", %d", a.Len)
		prUtil(&a.A, s[6], l-1, s)
		prUtil(&a.B, s[7], l-1, s)
	}
}

@ 유틸리티 필드 하나를 그 타입 부호에 따라 찍는다. |l|이 음수면 포인터는
건너뛰는데, 정점이 서로를 가리킬 때 무한 재귀에 빠지지 않으려는 것이다. 부호
|'Z'|는 아무것도 하지 않고, 그 밖의 부호는 나올 일이 없다.

@<표본 찍기 서브루틴@>=
func prUtil(u *gbgraph.Util, c byte, l int64, s string) {
	switch c {
	case 'I':
		fmt.Printf("[%d]", u.I)
	case 'S':
		if u.S != "" {
			fmt.Printf("[\"%s\"]", u.S)
		} else {
			fmt.Print("[\"(null)\"]")
		}
	case 'A':
		if l < 0 {
			return
		}
		fmt.Print("[")
		if u.A == nil {
			fmt.Print("NULL")
		} else {
			prArc(u.A, l, s)
		}
		fmt.Print("]")
	case 'V':
		if l < 0 {
			return
		}
		fmt.Print("[")
		prVert(u.V, l, s)
		fmt.Print("]")
	}
}

@* 색인. 늘 하던 대로 식별자들이 어디서 쓰이고 어디서 정의되는지 보이는 목록으로
끝맺는다.
