// Command test_sample exercises most of the GraphBase generators and prints
// salient characteristics of each graph, as an installation/portability check.
// It is a Go port of Knuth's TEST_SAMPLE program.
//
// The original is meant to be diffed against golden files (sample.correct for
// stdout, test.correct for the saved test.gb).  Running this port matches
// sample.correct except for a few spots:
//
//   - raman's reduce parameter is a bool here, so its ID renders as 1, not the
//     C call's 4 (the graph itself is identical);
//   - the original adds a stray vertex to a graph's data area with a pointer
//     hack before saving test.gb; that has no idiomatic Go equivalent, so it is
//     omitted and test.gb holds only the complement graph;
//   - two genuine library divergences this test surfaces: gb-gates partial_gates
//     reduces to a slightly different gate count, and gb-plane PlaneMiles uses a
//     different util_types/edge set than the reference.
//
// Failures still print SGB's numeric panic codes (panicCode maps the standard
// error sentinels), and everything else matches, since the generators are
// otherwise bit-exact.  Run it from the repository root so that "data/" resolves
// (the generators read their .dat files there).
package main

import (
	"errors"
	"fmt"
	"os"

	gbbasic "github.com/sjnam/go-sgb/gb-basic"
	gbbooks "github.com/sjnam/go-sgb/gb-books"
	gbecon "github.com/sjnam/go-sgb/gb-econ"
	gbgames "github.com/sjnam/go-sgb/gb-games"
	gbgates "github.com/sjnam/go-sgb/gb-gates"
	gbgraph "github.com/sjnam/go-sgb/gb-graph"
	gbio "github.com/sjnam/go-sgb/gb-io"
	gblisa "github.com/sjnam/go-sgb/gb-lisa"
	gbmiles "github.com/sjnam/go-sgb/gb-miles"
	gbplane "github.com/sjnam/go-sgb/gb-plane"
	gbraman "github.com/sjnam/go-sgb/gb-raman"
	gbrand "github.com/sjnam/go-sgb/gb-rand"
	gbroget "github.com/sjnam/go-sgb/gb-roget"
	gbsave "github.com/sjnam/go-sgb/gb-save"
	gbwords "github.com/sjnam/go-sgb/gb-words"
)

// dst is a probability distribution with frequencies 50%, 25%, 25%.
var dst = []int64{0x20000000, 0x10000000, 0x10000000}

// wtVector just barely exceeds the maximum weight threshold GB_WORDS allows.
var wtVector = []int64{100, -80589, 50000, 18935, -18935, 18935, 18935, 18935, 18935}

func main() {
	gbio.DataDirectory = "data/"
	fmt.Println("GraphBase samples generated by test_sample:")

	// Save a graph to be restored later.  (The original also splices in a stray
	// "Testing" vertex via a pointer hack; that has no Go equivalent, so test.gb
	// holds just the complement graph.)
	g, _ := gbrand.RandomGraph(3, 10, 1, true, false, nil, dst, 1, 2, 1)
	gg, _ := gbbasic.Complement(g, true, true, false)
	if _, err := gbsave.SaveGraph(gg, "test.gb"); err != nil {
		fmt.Fprintf(os.Stderr, "Couldn't save test.gb: %v\n", err)
	}

	// A graph that needs no input data and no random numbers (GB_GRAPH/GB_RAMAN).
	printSample(adapt(gbraman.Raman(31, 3, 0, true)))(4)

	// GB_BASIC's coordinate wraparound: coordinates 32 and 33 should wrap.
	printSample(adapt(gbbasic.Board(1, 1, 2, -33, 1, -0x40000000-0x40000000, true)))(2000)

	// GB_BASIC character codes.
	printSample(adapt(gbbasic.Subsets(32, 18, 16, 0, 999, -999, 0x80000000, true)))(1)

	// Restore the saved graph, randomize its lengths, and take a gunion.
	if g2, err := gbsave.RestoreGraph("test.gb"); err != nil {
		printSample(nil, err)(2)
	} else if err := gbrand.RandomLengths(g2, false, 10, 12, dst, 2); err != nil {
		fmt.Printf("\nFailure code %s returned by random_lengths!\n", panicCode(err))
	} else {
		gg2, _ := gbrand.RandomGraph(3, 10, 1, true, false, nil, dst, 1, 2, 1) // same as before
		printSample(adapt(gbbasic.Gunion(g2, gg2, true, false)))(2)
	}

	// Partial evaluation of a RISC circuit (intricate pointer manipulation).
	riscG, _ := gbgates.Risc(0)
	printSample(adapt(gbgates.PartialGates(riscG, 1, 43210, 98765, nil)))(79)

	// Reading data files, GB_SORT, and heavy randomization.
	printSample(adapt2(gbbooks.Book("homer", 500, 400, 2, 12, 10000, -123456, 789)))(81)
	printSample(adapt(gbecon.Econ(40, 0, 400, -111)))(11)
	printSample(adapt(gbgames.Games(60, 70, 80, -90, -101, 60, 0, 999999999)))(14)
	printSample(adapt2(gbmiles.Miles(50, -500, 100, 1, 500, 5, 314159)))(20)
	printSample(adapt(gblisa.PlaneLisa(100, 100, 50, 1, 300, 1, 200, 50*299*199, 200*299*199)))(1294)
	printSample(adapt(gbplane.PlaneMiles(50, 500, -100, 1, true, 40000, 271818)))(14)
	printSample(adapt(gbrand.RandomBigraph(300, 3, 1000, -1, nil, dst, -500, 500, 666)))(3)
	printSample(adapt(gbroget.Roget(1000, 3, 1009, 1009)))(40)

	// A picky test that should fail the first time, succeed the second.
	printSample(adapt2(gbwords.Words(100, wtVector, 70000000, 69)))(5)
	wtVector[1]++
	printSample(adapt2(gbwords.Words(100, wtVector, 70000000, 69)))(5)
	printSample(adapt2(gbwords.Words(0, nil, 0, 69)))(5555)
}

// adapt and adapt2 reduce the various generator return signatures to a
// (graph, error) pair so printSample can take them uniformly.
func adapt(g *gbgraph.Graph, err error) (*gbgraph.Graph, error) { return g, err }
func adapt2[T any](g *gbgraph.Graph, _ T, err error) (*gbgraph.Graph, error) {
	return g, err
}

// printSample returns a closure taking the sampled vertex index, so generator
// calls read naturally as printSample(gen(...))(n).  It prints the graph's
// global characteristics and the nth vertex, then recycles the graph; a nil
// graph (failed generation) prints the panic code instead.
func printSample(g *gbgraph.Graph, err error) func(n int64) {
	return func(n int64) {
		fmt.Print("\n")
		if err != nil || g == nil {
			fmt.Printf("Ooops, we just ran into panic code %s!\n", panicCode(err))
			return
		}
		printGlobal(g)
		printVertex(g, n)
		g.Recycle()
	}
}

// printGlobal prints the id, size, util_types, and graph-level utility fields.
func printGlobal(g *gbgraph.Graph) {
	s := g.UtilTypes
	fmt.Printf("\"%s\"\n%d vertices, %d arcs, util_types %s", g.ID, g.N, g.M, s)
	prUtil(g.UU, s[8], 0, s)
	prUtil(g.VV, s[9], 0, s)
	prUtil(g.WW, s[10], 0, s)
	prUtil(g.XX, s[11], 0, s)
	prUtil(g.YY, s[12], 0, s)
	prUtil(g.ZZ, s[13], 0, s)
	fmt.Print("\n")
}

// printVertex prints detailed information about the nth vertex of g.
func printVertex(g *gbgraph.Graph, n int64) {
	fmt.Printf("V%d: ", n)
	if n >= g.N || n < 0 {
		fmt.Print("index is out of range!\n")
		return
	}
	prVert(&g.Vertices[n], 1, g.UtilTypes)
	fmt.Print("\n")
}

// prVert prints a vertex: its name, utility fields, and (when l>0) its arcs.
func prVert(v *gbgraph.Vertex, l int, s string) {
	if v == nil {
		fmt.Print("NULL")
		return
	}
	// The original also prints "ONE" for a boolean-constant vertex; the Go
	// gb-gates port has no such sentinel, so that case does not arise here.
	fmt.Printf("\"%s\"", v.Name)
	prUtil(v.U, s[0], l-1, s)
	prUtil(v.V, s[1], l-1, s)
	prUtil(v.W, s[2], l-1, s)
	prUtil(v.X, s[3], l-1, s)
	prUtil(v.Y, s[4], l-1, s)
	prUtil(v.Z, s[5], l-1, s)
	if l > 0 {
		for a := v.Arcs; a != nil; a = a.Next {
			fmt.Print("\n   ")
			prArc(a, 1, s)
		}
	}
}

// prArc prints an arc: its tip and (when l>0) its length and utility fields.
func prArc(a *gbgraph.Arc, l int, s string) {
	fmt.Print("->")
	prVert(a.Tip, 0, s)
	if l > 0 {
		fmt.Printf(", %d", a.Len)
		prUtil(a.A, s[6], l-1, s)
		prUtil(a.B, s[7], l-1, s)
	}
}

// prUtil prints one utility field according to its type code c.  Level l is 0
// for terse output and -1 when pointer fields should be omitted (to bound the
// recursion).
func prUtil(u any, c byte, l int, s string) {
	switch c {
	case 'I':
		i, _ := u.(int64)
		fmt.Printf("[%d]", i)
	case 'S':
		str, ok := u.(string)
		if !ok {
			str = "(null)"
		}
		fmt.Printf("[\"%s\"]", str)
	case 'A':
		if l < 0 {
			return
		}
		fmt.Print("[")
		if a, _ := u.(*gbgraph.Arc); a == nil {
			fmt.Print("NULL")
		} else {
			prArc(a, l, s)
		}
		fmt.Print("]")
	case 'V':
		if l < 0 {
			return
		}
		fmt.Print("[")
		v, _ := u.(*gbgraph.Vertex)
		prVert(v, l, s)
		fmt.Print("]")
	}
}

// panicCode maps the standard graph error sentinels back to the numeric panic
// codes the original prints; unknown errors fall back to their message.
func panicCode(err error) string {
	switch {
	case err == nil:
		return "0"
	case errors.Is(err, gbgraph.ErrNoRoom):
		return "1"
	case errors.Is(err, gbgraph.ErrEarlyDataFault):
		return "10"
	case errors.Is(err, gbgraph.ErrLateDataFault):
		return "11"
	case errors.Is(err, gbgraph.ErrSyntaxError):
		return "20"
	case errors.Is(err, gbgraph.ErrBadSpecs):
		return "30"
	case errors.Is(err, gbgraph.ErrVeryBadSpecs):
		return "40"
	case errors.Is(err, gbgraph.ErrMissingOperand):
		return "50"
	case errors.Is(err, gbgraph.ErrInvalidOperand):
		return "60"
	case errors.Is(err, gbgraph.ErrImpossible):
		return "90"
	}
	return err.Error()
}
